services:
  web:
    image: shinsenter/symfony:latest
    volumes:
      - ./proyecto:/var/www/html
    environment:
      APP_USER: "bryan"
      APP_GROUP: "bryan"
      APP_UID: "1000"
      APP_GUID: "1000"
    ports:
      - 8000:80
  db:
    image: mysql:9.1
    restart: always
    environment:
      MYSQL_DATABASE: db
      MYSQL_ROOT_PASSWORD: symfony
      MYSQL_USER: symfony
      MYSQL_PASSWORD: symfony
    ports:
      - 3036:80
    volumes:
      - ./db_data:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      - PMA_ARBITRARY=1